# Generated by Django 4.1.3 on 2023-01-08 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssg_online_election_app', '0003_remove_vote_vote_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='ssg_online_election_app.category'),
        ),
    ]
