# Generated by Django 4.1.3 on 2023-01-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssg_online_election_app', '0004_alter_candidate_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='img_path',
            field=models.ImageField(upload_to='proj_ssg/files/profiles'),
        ),
    ]
